# Form implementation generated from reading ui file 'youtube_summarizer.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 12, 781, 561))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.apiKeyLayout = QtWidgets.QHBoxLayout()
        self.apiKeyLayout.setObjectName("apiKeyLayout")
        self.apiKeyLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.apiKeyLineEdit.setObjectName("apiKeyLineEdit")
        self.apiKeyLayout.addWidget(self.apiKeyLineEdit)
        self.saveButton = QtWidgets.QPushButton(parent=self.widget)
        self.saveButton.setObjectName("saveButton")
        self.apiKeyLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.apiKeyLayout)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.levelOfDetailComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.levelOfDetailComboBox.setObjectName("levelOfDetail")
        self.levelOfDetailComboBox.addItem("")
        self.levelOfDetailComboBox.addItem("")
        self.levelOfDetailComboBox.addItem("")
        self.horizontalLayout.addWidget(self.levelOfDetailComboBox)
        self.languageComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.languageComboBox.setObjectName("language")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.horizontalLayout.addWidget(self.languageComboBox)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apiKeyLineEdit.setPlaceholderText(_translate("MainWindow", "Google API Key"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Youtube-URL"))
        self.levelOfDetailComboBox.setPlaceholderText(_translate("MainWindow", "Level of detail"))
        self.levelOfDetailComboBox.setItemText(0, _translate("MainWindow", "Short"))
        self.levelOfDetailComboBox.setItemText(1, _translate("MainWindow", "Medium"))
        self.levelOfDetailComboBox.setItemText(2, _translate("MainWindow", "Very detailed"))
        self.languageComboBox.setPlaceholderText(_translate("MainWindow", "Language"))
        self.languageComboBox.setItemText(0, _translate("MainWindow", "English"))
        self.languageComboBox.setItemText(1, _translate("MainWindow", "German"))
        self.languageComboBox.setItemText(2, _translate("MainWindow", "French"))
        self.languageComboBox.setItemText(3, _translate("MainWindow", "Spanish"))
        self.pushButton.setText(_translate("MainWindow", "Summarize"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", "Summary"))
